//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class state_
    {
        public int id { get; set; }
        public Nullable<int> isactive { get; set; }
        public Nullable<System.DateTime> c_date { get; set; }
        public Nullable<System.DateTime> u_date { get; set; }
        public string state_name { get; set; }
        public string country_name { get; set; }
    }
}
