//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApprovedOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblApprovedOrder()
        {
            this.tblPlacdOrders = new HashSet<tblPlacdOrder>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ChefId { get; set; }
        public string MobileNo { get; set; }
        public string C_Address { get; set; }
    
        public virtual tblChef tblChef { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPlacdOrder> tblPlacdOrders { get; set; }
    }
}
