//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPostRecipe
    {
        public int id { get; set; }
        public string DishName { get; set; }
        public string Discrip { get; set; }
        public byte[] Pic { get; set; }
        public string Ingre { get; set; }
    }
}
